//
//  HomePresenter.swift
//  TiendeoTest
//
//  Created Jesús Solé on 06/01/2019.
//  Copyright © 2019 JSolec. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter: HomePresenterProtocol {

    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getOffers() {
        self.interactor?.getOffers()
    }
    
    func getNumberOfElements(section: Int) -> Int? {
        return section == 0 ? self.interactor?.getNumberOfCatalogs() : self.interactor?.getNumberOfCoupons()
    }
    
    func getTitle(section: Int) -> String {
        return section == 0 ? "kCatalogs".localize.uppercased() : "kCoupons".localize.uppercased()
    }
    
    func updateOffers() {
        self.view?.updateOffers()
    }
    
    func showError(error: Error) {
        self.view?.showError(error: error)
    }
    
    func getBusisness(indexPath: IndexPath) -> String? {
        return indexPath.section == 0 ? self.interactor?.getCatalogBusisness(index: indexPath.row)
            : self.interactor?.getCouponBusisness(index: indexPath.row)
    }
    
    func getEndDate(indexPath: IndexPath) -> String? {
        return indexPath.section == 0 ? self.interactor?.getCatalogEndDate(index: indexPath.row)
            : self.interactor?.getCouponEndDate(index: indexPath.row)
    }
}
