//
//  StoreProtocols.swift
//  TiendeoTest
//
//  Created Jesús Solé on 12/01/2019.
//  Copyright © 2019 JSolec. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import CoreLocation

//MARK: Wireframe -
protocol StoreWireframeProtocol: class {

}
//MARK: Presenter -
protocol StorePresenterProtocol: class {
    func getStoreName() -> String?
    func getStoreCompleteAddress() -> String?
    func getStorePhone() -> String?
    func getStoreWeb() -> String?
    func getStoreLocation() -> CLLocationCoordinate2D?
}

//MARK: Interactor -
protocol StoreInteractorProtocol: class {

    var presenter: StorePresenterProtocol?  { get set }
    
    func setStore(store: StoreModel)
    
    func getStoreName() -> String?
    func getStoreAddress() -> String?
    func getStorePostalCode() -> String?
    func getStoreCity() -> String?
    func getStorePhone() -> String?
    func getStoreWeb() -> String?
    func getStoreLocation() -> CLLocationCoordinate2D?
}

//MARK: View -
protocol StoreViewProtocol: class {

  var presenter: StorePresenterProtocol?  { get set }
}
