//
//  StoreRouter.swift
//  TiendeoTest
//
//  Created Jesús Solé on 12/01/2019.
//  Copyright © 2019 JSolec. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class StoreRouter: StoreWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(store: StoreModel) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: Controllers.Store) as! StoreViewController
        let interactor = StoreInteractor()
        let router = StoreRouter()
        let presenter = StorePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        interactor.setStore(store: store)
        
        return view
    }
}
