//
//  StoreInteractor.swift
//  TiendeoTest
//
//  Created Jesús Solé on 12/01/2019.
//  Copyright © 2019 JSolec. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreLocation

class StoreInteractor: StoreInteractorProtocol {

    weak var presenter: StorePresenterProtocol?
    private var store: StoreModel!
    
    func setStore(store: StoreModel) {
        self.store = store
    }
    
    func getStoreName() -> String? {
        return self.store.storeName
    }
    
    func getStoreAddress() -> String? {
        return self.store.storeAddress
    }
    
    func getStorePostalCode() -> String? {
        return self.store.storeZipCode
    }
    
    func getStoreCity() -> String? {
        return self.store.storeCity
    }
    
    func getStorePhone() -> String? {
        return self.store.phoneNumber
    }
    
    func getStoreWeb() -> String? {
        return self.store.webUrl
    }
    
    func getStoreLocation() -> CLLocationCoordinate2D? {
        if let latitude = self.store.latitude?.doubleValue,
            let longitude = self.store.longitude?.doubleValue {
            return CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
        }
        return nil
    }
}
