//
//  StorePresenter.swift
//  TiendeoTest
//
//  Created Jesús Solé on 12/01/2019.
//  Copyright © 2019 JSolec. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreLocation

class StorePresenter: StorePresenterProtocol {

    weak private var view: StoreViewProtocol?
    var interactor: StoreInteractorProtocol?
    private let router: StoreWireframeProtocol

    init(interface: StoreViewProtocol, interactor: StoreInteractorProtocol?, router: StoreWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getStoreName() -> String? {
        return self.interactor?.getStoreName()
    }
    
    func getStoreCompleteAddress() -> String? {
        var completeAddress = ""
        
        if let address = self.interactor?.getStoreAddress() {
            completeAddress += address
        }
        
        if let postalCode = self.interactor?.getStorePostalCode() {
            completeAddress += ", " + postalCode
        }
        
        if let city = self.interactor?.getStoreCity() {
            completeAddress += ", " + city
        }
        return completeAddress.trimmingCharacters(in: .whitespacesAndNewlines)
    }
    
    func getStorePhone() -> String? {
        return self.interactor?.getStorePhone()
    }
    
    func getStoreWeb() -> String? {
        return self.interactor?.getStoreWeb()
    }
    
    func getStoreLocation() -> CLLocationCoordinate2D? {
        return self.interactor?.getStoreLocation()
    }

}
