//
//  SplashViewController.swift
//  TiendeoTest
//
//  Created Jesús Solé on 12/01/2019.
//  Copyright © 2019 JSolec. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashViewController: UIViewController, SplashViewProtocol {

	var presenter: SplashPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.setupView()
        self.getOffers()
    }
    
    private func setupView() {
        
    }
    
    func getOffers() {
        self.presenter?.getOffers()
    }
    
    func showError(error: Error) {
        AlertsManager.showAlertMessage(controller: self,
                                       title: "kError".localize,
                                       message: error.localizedDescription,
                                       buttonString: "kOk".localize)
    }
}
